### ISSUE TITLE
Need the ability to filter the PTI log stream being collected

### ISSUE THREAD

**Issue by dmfiore** [SiliconLabs/java_packet_trace_library#38]
Hi guys.  Question on silabs-pti.jar
Can I filter on a regex/keyword?
What I do now is collect all streams to individual log files.
Then I need to strip the finished logs for everything but the 'latency' keyword.
Then I parse out the time deltas per seqNum from transmit source to the receiving sources.
The problem I hit is the huge enormity of these logs
I have a 200 node network I'm collecting from all, and since I'm constantly send bcast and other control and data packets its like a 1000 pps for receiving devices.
This works for a short period of 5-15 mins.   But I'm being asked to run longer duration testing like hours.
...SO, maybe I can avoid collecting every discrete PTI packet and just log the rare ones I am interested and avoid the stripping I do on my side??
(BTW, been using it a lot last 1-2 months, works great !) 

Timotej Ećimović
I don't think we have any filtering, but it's really easy to add.

**Comment by dmfiore** [comment]
Here is an example of the pti.log collected for one device, and then the stripped version of it for what I'm interested in.
[pti__base_10.4.186.7.log](https://github.com/SiliconLabs/java_packet_trace_library/files/9507821/pti__base_10.4.186.7.log)
[dbg_pti__base_10.4.186.7.log](https://github.com/SiliconLabs/java_packet_trace_library/files/9507824/dbg_pti__base_10.4.186.7.log)

**Comment by tecimovic** [comment]
@dmfiore : your example filters for events of type "latency". It would be easy to simply add filter for any type of debug message.

Are there any other filters you desire?

**Comment by dmfiore** [comment]
None at this time, but yeah give me a regex or whatever.  Thanks!

**Comment by tecimovic** [comment]
Fixed in: https://github.com/SiliconLabs/java_packet_trace_library/pull/39
